sitionix:
  cors:
    allowed-origins:
      - "http://localhost:3000"
server:
  port: 8080
  servlet:
    context-path: /bffssox
api:
  rest:
    client:
      athssox:
        base-path: http://localhost:9090/authsox