sitionix:
  cors:
    allowed-origins:
      - "https://localhost:3000"
      - "https://localhost:3001"
      - "https://localhost:3002"
      - "https://localhost:3003"
api:
  rest:
    client:
      athssox:
        base-path: http://authorisationservice-sox:9090/authsox
      atmssox:
        base-path: http://automationservice-sox:9083/atmssox
      stsssox:
        base-path: http://siteservice-sox:9080/stsssox
      wagssox:
        base-path: http://workspaceaggregationservice-sox:9082/wagssox
forge:
  user-jwt:
    auth-base-url: http://authorisationservice-sox:9090/authsox
  security:
    targets:
      sitionixAuth:
        host: authorisationservice-sox
      sitionixAutomation:
        host: automationservice-sox
      sitionixSite:
        host: siteservice-sox
      sitionixWorkspace:
        host: workspaceaggregationservice-sox
